//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fridgefood
{
    using System;
    using System.Collections.Generic;
    
    public partial class FridgeItem
    {
        public int Id { get; set; }
        public Nullable<int> FreezingTime { get; set; }
        public Nullable<int> FridgeTime { get; set; }
        public Nullable<int> ExpiryReminder { get; set; }
        public Nullable<double> LowStockReminder { get; set; }
        public string LowStockReminderUnit { get; set; }
        public Nullable<double> DailyConsumption { get; set; }
        public string DailyConsumptionUnit { get; set; }
        public Nullable<int> FridgeId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string ItemUnit { get; set; }
        public string Category { get; set; }
    }
}
