//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fridgefood
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeNotification
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> MealDate { get; set; }
        public string MealTime { get; set; }
        public string Reply { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> RecieverId { get; set; }
        public Nullable<int> FridgeId { get; set; }
        public Nullable<int> RecipeId { get; set; }
    }
}
